# 服务设置
[server]
    name = "web-room"
    addr = ":8080"

# 设置日志模式
[server.logger]
    level = "debug"

# 数据结构类
[database]
    driver = "mysql"

# 数据结构配置
[mysql]
    dbHost = "127.0.0.1"
    dbPort = "3306"
    dbName = "mydb"
    dbParams = "parseTime=true&loc=Local&charset=utf8"
    dbUser = "Pudge"
    dbPasswd = "Pudge123"
